# Check all mandatory variables are not empty

- name: Check all mandatory variables are not empty
  fail: msg="Certain variable inside user_variable.yaml {{ item }} is empty"
  when: item == ""
  loop:
  # default variables
    - "{{ default_yaml_files_base_path }}"
    - "{{ storage_type }}"

# Check if storage_type == "persistent"
- name: Check persistent variables
  fail: msg="persistent variable inside user_variable.yaml is empty"
  when: storage_type == "persistent" and item == ""
  loop:
    - "{{ preserve_pv }}"
