# Check if previous Federator.ai installed
- name: Get Pods info (also connection test)
  community.kubernetes.k8s_info:
    kind: Pod
  register: pod_list

- name: Parse pods info to get namespace
  set_fact:
    previous_alameda_namespace: "{{ pod_list |to_json | from_json| json_query(\"resources[?contains(metadata.name, 'federatorai-operator-')||contains(metadata.name, 'alameda-ai-')].metadata.namespace\")}}"

- name: Set previous_alameda_namespace variable
  set_fact:
    previous_alameda_namespace: "{% if previous_alameda_namespace | length > 0 %}{{ previous_alameda_namespace[0] }}{% else %}{{ '' }}{% endif %}"

- name: Debug - previous_alameda_namespace
  debug:
    var: previous_alameda_namespace

- name: Parse pods info to get image tag list
  set_fact:
    image_tag_list: "{{ pod_list |to_json | from_json| json_query(\"resources[?contains(metadata.name, 'federatorai-operator-')||contains(metadata.name, 'alameda-ai-')].spec.containers[0].image\") }}"

- name: Get federatorai_version 
  set_fact:
    federatorai_version: "{% if image_tag_list |length > 0 %}{{ image_tag_list[0].split(':')[1] }}{% else %}{{ '' }}{% endif %}"

- name: Debug - federatorai_version
  debug:
    var: federatorai_version

